Settings: Add BluetoothBatteryMetadataFetcher to PowerUsageFeatureGoogle
Required for battery widget.

08-29 00:23:05.868 29957 30399 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #14
08-29 00:23:05.868 29957 30399 E AndroidRuntime: Process: com.android.settings, PID: 29957
08-29 00:23:05.868 29957 30399 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/settings/fuelgauge/BluetoothBatteryMetadataFetcher;
08-29 00:23:05.868 29957 30399 E AndroidRuntime: 	at com.google.android.settings.fuelgauge.BatteryBroadcastReceiver.lambda$onReceive$0(Unknown Source:0)
08-29 00:23:05.868 29957 30399 E AndroidRuntime: 	at com.google.android.settings.fuelgauge.BatteryBroadcastReceiver.$r8$lambda$hXivAYsMRi0SFVbKWyMDhmZt7nA(Unknown Source:0)
08-29 00:23:05.868 29957 30399 E AndroidRuntime: 	at com.google.android.settings.fuelgauge.BatteryBroadcastReceiver$$ExternalSyntheticLambda0.run(Unknown Source:4)
08-29 00:23:05.868 29957 30399 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
08-29 00:23:05.868 29957 30399 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-29 00:23:05.868 29957 30399 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-29 00:23:05.868 29957 30399 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
08-29 00:23:05.868 29957 30399 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.settings.fuelgauge.BluetoothBatteryMetadataFetcher
08-29 00:23:05.868 29957 30399 E AndroidRuntime: 	... 7 more

Signed-off-by: Adithya R <gh0strider.2k18.reborn@gmail.com>